services:
  nginx:
    image: rubenfabiodev/fullcycle-3-docker-nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

  app:
    image: rubenfabiodev/fullcycle-3-docker-node:latest
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    restart: always
    tty: true
    ports:
      - "3000:3000"
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://db:3306", "-timeout", "20s"]
    command: ["npm", "run", "start"]
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
